# Generated by Django 4.2.2 on 2023-06-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('company', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Издатель')),
                ('languages', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Поддерживаемые Языки')),
                ('original_size', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Размер после установки')),
                ('repack_size', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Размер репака')),
                ('torrent_link_1337x', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на торрент-файл 1337x')),
                ('torrent_link_magnet', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на торрент-файл magnet')),
                ('torrent_link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на торрент-файл')),
                ('torrent_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Торрент-файл')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('tag', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Тэг')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
