# Generated by Django 4.2.2 on 2023-06-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='Название'),
        ),
    ]
