# Generated by Django 4.2.2 on 2023-06-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_game_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('channel', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Канал')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название Канала')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(blank=True, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('username', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='First_name')),
                ('last_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Last_name')),
                ('phone_number', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Phone_number')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
