# Generated by Django 4.2.2 on 2023-08-13 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_user_date_alter_game_description_logging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.user'),
        ),
    ]
